dataset:
  subset_dir: "coco_subset_images"
  image_dir: "coco_subset_images/images"
  subset_file: "coco_multimodal_subset.json"
  num_distractors: 11 # So N=12 (1 GT + 11 distractors)

training:
  batch_size: 32
  learning_rate: 0.0003 # More conservative LR for adapter tuning
  weight_decay: 0.01 # Stronger L2 to reduce overfitting
  label_smoothing: 0.2
  dropout_p: 0.6
  early_stopping_patience: 2
  min_delta: 0.002
  epochs: 25 # Reduced to 25 to save time
  k_shots: [8, 32] # add 16, 32 if have time
  device: "cuda"

models:
  clip_vit: "ViT-B/32"
  clip_rn50: "RN50"
  
wandb:
  project: "coco_caption_classification"
  entity: "thailearncoding-ho-chi-minh-university-of-technology" # Add your wandb username/entity here
